### ISSUE TITLE
[help] Error in the PowerButton for theme.

### ISSUE THREAD

**Issue by stoxalpha** [obliviousofcraps/dotfiles#3]
Looks like i am missing the theme and I tried to download and copy the theme from web but i get a parsing error on doing that. Could you help here please. Git needs to create the discussion page soon.

![2020-09-02-095546_1920x1080_scrot](https://user-images.githubusercontent.com/38174924/91932058-c63faa00-ed02-11ea-9c69-e320b5c60cde.png)

**Comment by stoxalpha** [comment]
Hi @obliviousofcraps 
I verified that this is the file causing the trouble somehow. Will appreciate any suggestions.

/usr/share/rofi/themes/ArcoLinux-Nord.rasi

**Comment by stoxalpha** [comment]
Hi, I could make it work by pasting the ArchLinux-Nord.rasi in config.rasi. However q -> The mouse click is a little buggy where the the prompt stays on screen till the button is pressed for any of the power buttons. However moving the focus with keyboard works perfectly ?

**Comment by obliviousofcraps** [comment]
You can move the darkish.rasi to themes and then select that theme by running rofi-theme-selector. 

As for the mouse bug I too am still learning and don't know about that. The script is taken from [https://github.com/owl4ce/dotfiles](this) repo so you should check that out. Sorry for not being much of a help.
